version: "3.9"

services:
  mongo:
    build: ./backend/mongo
    restart: always
    ports:
      - 27017:27017
    #volumes:
    #  - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-tagme}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-example}
      ME_CONFIG_MONGODB_URL: ${MONGO_URL:-mongodb://root:example@mongo:27017/}