version: "3.9"

services:
  mongo:
    build: ./backend/mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./backend/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-example}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-tagme}